# Generated by Django 5.0 on 2024-01-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="username",
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
