# Generated by Django 5.0 on 2024-01-05 00:43

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="0", max_length=128, region="KR"
            ),
        ),
    ]
