# Generated by Django 5.0 on 2024-01-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_accountuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
