# Generated by Django 5.0 on 2024-01-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_accountuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="agearound",
            field=models.IntegerField(default=1),
        ),
    ]
