# Generated by Django 5.0 on 2024-01-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_accountuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
