# Generated by Django 5.0 on 2024-01-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_accountuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="https://mblogthumb-phinf.pstatic.net/MjAyMDExMDFfMTgy/MDAxNjA0MjI4ODc1NDMw.Ex906Mv9nnPEZGCh4SREknadZvzMO8LyDzGOHMKPdwAg.ZAmE6pU5lhEdeOUsPdxg8-gOuZrq_ipJ5VhqaViubI4g.JPEG.gambasg/%EC%9C%A0%ED%8A%9C%EB%B8%8C_%EA%B8%B0%EB%B3%B8%ED%94%84%EB%A1%9C%ED%95%84_%ED%95%98%EB%8A%98%EC%83%89.jpg?type=w800",
                null=True,
                upload_to="profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="gender",
            field=models.CharField(
                choices=[("여자", "여자"), ("남자", "남자")], default="남자", max_length=3
            ),
        ),
    ]
