# Generated by Django 5.0 on 2024-01-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_accountuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media\\profile_images"
            ),
        ),
    ]
