# Generated by Django 5.0 on 2024-01-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_accountuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="gender",
            field=models.CharField(
                choices=[("남자", "남자"), ("여자", "여자")], default="남자", max_length=3
            ),
        ),
    ]
