# Generated by Django 5.0 on 2024-01-08 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_accountuser_profile_image_alter_accountuser_gender"),
        ("accounts", "0008_alter_accountuser_gender"),
    ]

    operations = []
