# Generated by Django 4.2 on 2024-01-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="items",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
