# Generated by Django 5.0 on 2024-01-10 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_giftrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GiftRequest",
        ),
    ]
