# Generated by Django 5.0 on 2024-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_delete_giftrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.CharField(blank=True, max_length=10, null=True)),
                ("receiver", models.CharField(blank=True, max_length=10, null=True)),
                ("additionalinfo", models.TextField(blank=True, null=True)),
                ("minamount", models.BigIntegerField(blank=True, null=True)),
                ("maxamount", models.BigIntegerField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("occasion", models.CharField(blank=True, max_length=10, null=True)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
