# Generated by Django 5.0 on 2024-01-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_giftrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftrequest",
            name="receiver",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giftrequest",
            name="sender",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
