# Generated by Django 5.0 on 2024-01-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_giftrequest_receiver_alter_giftrequest_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftrequest",
            name="occasion",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="giftrequest",
            name="relationship",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
