# Generated by Django 4.2 on 2024-01-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_giftrequest_occasion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Three",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.BigIntegerField(blank=True, null=True)),
                ("receiver", models.BigIntegerField(blank=True, null=True)),
                (
                    "three_products",
                    models.CharField(blank=True, default="", max_length=200),
                ),
            ],
        ),
    ]
