# Generated by Django 5.0 on 2024-01-07 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
