# Generated by Django 5.0 on 2024-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0007_article_created_at_comment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
