# Generated by Django 5.0 on 2024-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0008_article_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_answered",
            field=models.BooleanField(default=False),
        ),
    ]
